var a = [1, 12, 93, 5];
var b = ["a", "apricot", "mango"];
//let c: number[] = [1,"apple","potato"];
var d = [null, undefined, 10, 15];
var ef = ["pie", null, ""];
var ab = [1, 12, 93, 5];
var bb = ["a", "apricot", "mango"];
//let cc: number[] = [1, "apple", "potato"]; 
var dd = [null, undefined, 10, 15];
var ee = ["pie", null, ""];
var one = [11, "monday"];
//let two:[number,string] =["monday",11];
//let three:[number,string]=["a","monkey"];
var four = [105, "owl"];
var five = [13, "bat"];
ee[13] = "elephant";
//ee[15]=false;
console.log(a[1]);
console.log(b[2]);
console.log(four[1], [2]);
